services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/opt/app
  ollama:
    image: ollama/ollama
    volumes:
      - ./var/ollama:/root/.ollama
    ports:
      - "11434:11434"
  omniparse:
    image: savatar101/omniparse:0.1
    ports:
      - "8000:8000"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 512mo HEAP
      - cluster.routing.allocation.disk.threshold_enabled=false
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
